//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSAppWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppDTEntities : DbContext
    {
        public AppDTEntities()
            : base("name=AppDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<NOVISITA> NOVISITA { get; set; }
        public DbSet<VISITA_REGISTRO> VISITA_REGISTRO { get; set; }
        public DbSet<vis_VISITA_CUSTOMER> vis_VISITA_CUSTOMER { get; set; }
        public DbSet<vis_Assigned_Visit> vis_Assigned_Visit { get; set; }
        public DbSet<INSTRUCTOR> INSTRUCTOR { get; set; }
        public DbSet<VISITA_ASSIGN> VISITA_ASSIGN { get; set; }
        public DbSet<vis_VISITA_REGISTRO> vis_VISITA_REGISTRO { get; set; }
        public DbSet<CUSTOMER> CUSTOMER { get; set; }
        public DbSet<vis_VISITA_REGISTRO_EMERGENTE> vis_VISITA_REGISTRO_EMERGENTE { get; set; }
        public DbSet<vis_VISITA_REGISTRO_Map> vis_VISITA_REGISTRO_Map { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<vis_VISITA_NOTVISIT> vis_VISITA_NOTVISIT { get; set; }
    }
}
