//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSAppWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOVISITA
    {
        public int novi_id { get; set; }
        public int vist_id { get; set; }
        public int inst_id { get; set; }
        public string novi_date { get; set; }
        public string novi_hora { get; set; }
        public string novi_reason { get; set; }
    }
}
